// Teamwork - visual campaign dashboard renderer.
//
// Converts raw campaign state, audit events, and verification logs into an
// elegant, high-information-density terminal & markdown status dashboard.
// Formatted with OLED pure dark & glass aesthetic cues, Mermaid dependency
// graphs, and health indicators.
//
// ASCII only: protocol artifact.

import {countDispatches} from './state.mjs';
import {resolveSpawnBudget, resolveMaxParallel} from './scheduler.mjs';

/**
 * Render a complete visual status report for the campaign.
 */
export function renderDashboard(campaign, options = {}) {
	if (!campaign) {
		return '### [TEAMWORK STATUS] No active campaign found in this workspace.';
	}

	const objective = campaign.objective ?? 'Unspecified';
	const phase = campaign.phase ?? 'scoping';
	const pattern = campaign.pattern ?? 'iterative-coding';
	const approved = campaign.approved === true;
	const milestones = Array.isArray(campaign.milestones) ? campaign.milestones : [];

	const totalMilestones = milestones.length;
	const doneMilestones = milestones.filter((m) => m.status === 'done' || m.verified === true).length;
	const progressPercent = totalMilestones > 0 ? Math.round((doneMilestones / totalMilestones) * 100) : 0;

	const budget = resolveSpawnBudget(campaign) ?? 16;
	const maxParallel = resolveMaxParallel(campaign) ?? 4;
	const events = options.events ?? [];
	const dispatches = options.dispatchesCount ?? 0;

	// Build Mermaid graph. Node keys must be plain identifiers: Chinese text or
	// punctuation in a node name breaks the graph, so the raw id is sanitized into
	// a key and everything human-readable (title) becomes a quoted label.
	const nodeKey = (raw) => String(raw).replace(/[^A-Za-z0-9_]/g, '_') || 'm';
	const graphLabel = (raw) => String(raw).replace(/\\/g, '\\\\').replace(/"/g, '\\"');
	let mermaid = '```mermaid\ngraph LR\n';
	if (milestones.length === 0) {
		mermaid += '  Start([Campaign Initialized]) --> Scoping[Scoping Phase]\n';
	} else {
		for (const m of milestones) {
			const mId = m.id ?? m.name ?? 'M';
			const label = m.title ? `${m.title} [${mId}]` : String(mId);
			const isDone = m.status === 'done' || m.verified === true;
			const shape = isDone ? `(["${graphLabel(label)} [DONE]"])` : `["${graphLabel(label)} [PENDING]"]`;
			const node = nodeKey(mId);
			const blockedBy = Array.isArray(m.blocked_by) ? m.blocked_by : [];
			if (blockedBy.length === 0) {
				mermaid += `  Start([Start]) --> ${node}${shape}\n`;
			} else {
				for (const b of blockedBy) {
					mermaid += `  ${nodeKey(b)} --> ${node}${shape}\n`;
				}
			}
		}
	}
	mermaid += '```\n';

	// Progress bar generator
	const barLength = 20;
	const filled = Math.round((progressPercent / 100) * barLength);
	const bar = '█'.repeat(filled) + '░'.repeat(Math.max(0, barLength - filled));

	const output = [
		'# 🌌 TEAMWORK MISSION CONTROL',
		'',
		`> **Objective**: ${objective}`,
		`> **Pattern**: \`${pattern}\` | **Phase**: \`${phase.toUpperCase()}\` | **Approved**: \`${approved ? 'YES' : 'NO'}\``,
		'',
		'### 📊 Campaign Progress',
		'```text',
		`Progress: [${bar}] ${progressPercent}% (${doneMilestones}/${totalMilestones} Milestones)`,
		`Dispatches: ${dispatches} / ${budget} max | Concurrency: ${maxParallel} parallel ceiling`,
		'```',
		'',
		'### 🧭 Milestone Topology',
		mermaid,
		'### 📋 Milestone Ledger',
		'| Milestone | Status | Owner | Verifier | Deliverables | Verification |',
		'|---|---|---|---|---|---|',
	];

	for (const m of milestones) {
		const mId = m.id ?? m.name ?? 'unknown';
		const label = m.title ? `${m.title} (${mId})` : mId;
		const status = m.status ?? 'pending';
		const owner = m.owner ?? 'unassigned';
		const verifier = m.verifier ?? 'critic';
		const deliverables = Array.isArray(m.deliverables) ? m.deliverables.join(', ') : 'none';
		const verified = m.verified ? '✅ SOUND' : '⏳ PENDING';
		output.push(`| **${label}** | \`${status}\` | ${owner} | ${verifier} | ${deliverables} | ${verified} |`);
	}

	output.push('', '---', '*Generated by Teamwork Dashboard Engine*');
	return output.join('\n');
}
